### ISSUE TITLE
Pull requests?

### ISSUE THREAD

**Issue by ngscheurich** [Yummygum/city-lights-syntax-vsc#18]
Howdy—this is a great theme! I'd like to add support for Elixir to this and [city-lights-icons-vsc](https://github.com/Yummygum/city-lights-icons-vsc) and submit a PR but I'm curious how you all feel about forks—the *NoDerivatives* portion of the license gives me pause. Thoughts?

**Comment by noudadrichem** [comment]
Hi @ngscheurich,

I'm glad you like the theme!

Of course you can make pull requests to optimize syntax highlighting or things you think can be better. Regarding the Icons, we want to maintain them ourselves. This to be consistent in styling of the icons.

Sincerely,

Noud

_Closing this because you can make a PR 😊_
