### ISSUE TITLE
Lost orange function params in latest Linux VS Code

### ISSUE THREAD

**Issue by locohost** [Yummygum/city-lights-syntax-vsc#61]
I'm using VS Code...

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.87-07826-g55ab70aff690

The params actually flash orange for just second when JS file loads, then they go grey.

![image](https://user-images.githubusercontent.com/132458/76693426-0a4acf80-663b-11ea-8474-c5e5ceece348.png)

**Comment by noudadrichem** [comment]
Hi @locohost,

I had the same problem. This is due to the new semantic highlighting feature of VSCode.
By disabling this you have the colors back. You can do so by adding:
`"editor.semanticHighlighting.enabled": false,` 
to your settings .json

See this tweet for reference: https://twitter.com/noudadrichem/status/1238836915736117248?s=20

**Comment by locohost** [comment]
Thank you @noudadrichem ! That's the trick :-)
